---
- hosts: all
  become: yes
  gather_facts: yes
  vars:
    runtime: docker

  tasks:
    - name: "Enable vi mode for {{ ansible_user }} user"
      lineinfile:
        path: "/home/{{ ansible_user }}/.bashrc"
        line: set -o vi

    - name: Update cache and install packages
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Change hostname
      hostname:
        name: "minikube{{ '-' + runtime | default(omit) }}"

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb != 0

    - name: Install and enable docker runtime
      block:
        - name: "Install {{ runtime }}"
          apt:
            name:
              - conntrack  # Kubernetes 1.19.2 requires
              - docker.io
            state: present

        - name: Create docker group
          group:
            name: docker

        - name: "Add {{ ansible_user }} user to docker group"
          user:
            groups: docker
            append: yes
            name: "{{ ansible_user }}"

        - name: Enable and start docker daemon
          systemd:
            name: docker.service
            enabled: yes
            state: started

      when: runtime == "docker"

    - name: Download minikube binary
      get_url:
        dest: /tmp/minikube-linux-amd64
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64

    - name: Install minikube
      command: install minikube-linux-amd64 /usr/local/bin/minikube
      args:
        chdir: /tmp
        creates: /usr/local/bin/minikube

    - name: Create kubectl softlink
      file:
        src: /usr/local/bin/minikube
        dest: /usr/local/bin/kubectl
        state: link
