---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Enable vi mode to vagrant user
      lineinfile:
        path: /home/vagrant/.bashrc
        line: set -o vi

    - name: Update cache and install packages
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Change hostname
      hostname:
        name: minikube

    - name: Disable swap
      command: swapoff -a

    - name: Install GPG key
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        keyring: /etc/apt/trusted.gpg.d/packages.virtualbox.gpg

    - name: Add repository and update cache
      apt_repository:
        repo: deb https://download.virtualbox.org/virtualbox/debian bionic contrib
        filename: virtualbox
        update_cache: yes

    - name: Install VirtualBox
      apt:
        name:
          - virtualbox-6.1
          - conntrack  # Kubernetes 1.19.2 requires
          - docker.io
        state: present

    - name: Create docker group
      group:
        name: docker

    - name: Add vagrant user to docker group
      user:
        groups: docker
        append: yes
        name: vagrant

    - name: Enable docker daemon
      systemd:
        name: docker.service
        enabled: yes
        state: started

    - name: Download minikube binary
      get_url:
        dest: /tmp
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64

    - name: Install minikube
      command: install minikube-linux-amd64 /usr/local/bin/minikube
      args:
        chdir: /tmp
        creates: /usr/local/bin/minikube

    - name: Start minikube using the Docker driver
      command: minikube start --driver=docker
      become_user: vagrant